apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://jerry-homelab-kube-kv.vault.azure.net/
      tenantId: fbdf800e-c040-4258-9ad3-6bbfb164500d
      authSecretRef:
        clientId:
          name: az-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: az-creds
          key: ClientSecret
          namespace: external-secrets
        