apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-ssh-secret
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: truenas-ssh-secret
    creationPolicy: Owner
  data:
    - secretKey: id_rsa
      remoteRef:
        # KEY_VAULT_SECRET_NAME should be the name of the secret in Key Vault that will
        # contain the private key text (the full private key, PEM format). Replace below.
        key: "truenas-storage"
        property: "" # empty means use the whole secret value
