apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      # Replace <VAULT_NAME> below with your Key Vault name (no https://)
      vaultUrl: "https://jerry-homelab-kube-kv.vault.azure.net/"
      # authSecretRef points to a Kubernetes Secret (azure-creds) that holds
      # tenantId, clientId, clientSecret. Create that secret in namespace
      # `external-secrets` (template provided).
      authSecretRef:
        clientId:
          name: azure-creds
          key: clientId
        clientSecret:
          name: azure-creds
          key: clientSecret
        tenantId:
          name: azure-creds
          key: tenantId
