# TEMPLATE - create real secret with SealedSecrets or SOPS; DO NOT COMMIT PRIVATE KEYS
apiVersion: v1
kind: Secret
metadata:
  name: truenas-ssh-secret
  namespace: democratic-csi
type: Opaque
stringData:
  # private key contents for SSH access (replace with your key)
  id_rsa: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...REPLACE_WITH_PRIVATE_KEY...
    -----END OPENSSH PRIVATE KEY-----
  # optionally a passphrase (if used)
  passphrase: ""
