apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: "0.13.10"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  values:
    controller:
      replicaCount: 2
      enabled: true
    speaker:
      enabled: true
