apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: "0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  values:
    controller:
      enabled: true # Enable the controller component
      replicaCount: 2 # Deploy 2 replicas for high availability
    speaker:
      enabled: true # Enable the speaker component
