apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.13.10  # Or latest
      sourceRef:
        kind: HelmRepository
        name: metallb-system
        namespace: metallb-system
  interval: 10m
  values:
    controller:
      logLevel: info