apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secret
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/controllers/base/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m
  wait: true