# -----------------------------------------------------------------------------
# Root Kustomization for Talos Cluster
#
# This Kustomization file groups all major application and infrastructure
# resources for the cluster. It allows you to deploy and manage multiple
# Kustomization resources (apps, networking, CRDs, etc.) together.

#If the file is not in here it will not be deployed by Flux.

#
# Resources included:
# - podinfo.yaml: Deploys the Podinfo app.
# - nginx.yaml: Deploys the NGINX Ingress controller and related resources.
# - metallb-crds.yaml: Installs MetalLB CRDs.
# - metallb.yaml: Deploys MetalLB and its configuration.
#
# For more details, see:
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
# -----------------------------------------------------------------------------


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx.yaml
  - metallb-crds.yaml
  - metallb.yaml
  - homepage.yaml
  - tautulli.yaml