#This file lets you group multiple Kustomization resources together. 
#It's not required by Flux, but it's useful if you want to deploy many apps with one 
#kustomize build or have Flux sync everything under clusters/talos-cluster/.

#This file defines which parts of your Git repo Flux should apply to the cluster.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo.yaml
  - nginx.yaml