#This file lets you group multiple Kustomization resources together. 
#It's not required by Flux, but it's useful if you want to deploy many apps with one 
#kustomize build or have Flux sync everything under clusters/talos-cluster/.

#Think of it as an aggregator: you can run kubectl apply -k clusters/talos-cluster/ and 
#apply all the defined apps at once (assuming your GitRepository is already bootstrapped).

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx.yaml
  - podinfo.yaml
