# This file is used by Flux to apply the MetalLB CRDs before any MetalLB resources.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 5m
  path: clusters/talos-cluster/networking/metallb/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m
  wait: true
