# This file is used by Flux (NOT Kubernetes) to deploy MetalLB resources into the metallb-system namespace.
# Every 5 minutes, look in the ./networking/metallb folder in the flux-system Git repo.
# Apply everything in that folder into the metallb-system namespace.
# Wait up to 1 minute. Clean up any deleted resources.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 5m
  path: clusters/talos-cluster/networking/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: metallb-system
  timeout: 1m
  wait: true
dependsOn:
  - name: metallb-crds
    namespace: flux-system
