apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 5m
  path: networking/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: metallb-system
  timeout: 1m
  wait: true
  dependsOn:
    - name: metallb-crds
      namespace: flux-system
