# -----------------------------------------------------------------------------
# MetalLB System Kustomization for FluxCD
#
# This manifest defines a FluxCD Kustomization resource to deploy MetalLB and its
# configuration to the cluster.
# - Applies all MetalLB manifests (namespace, HelmRelease, IP pools, etc.) from the specified path.
# - Ensures resources are deployed into the metallb-system namespace.
# - Waits for MetalLB CRDs to be established before applying (dependsOn).
# - Prunes resources removed from the path.
#
# Key fields:
# - path: Location of MetalLB manifests in the repo.
# - targetNamespace: Namespace to deploy resources into.
# - dependsOn: Ensures CRDs are applied first.
#
# For more details, see:
# https://fluxcd.io/docs/components/kustomize/kustomization/
# -----------------------------------------------------------------------------

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 5m
  path: clusters/talos-cluster/networking/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: metallb-system
  timeout: 1m
  wait: true
  dependsOn:
    - name: metallb-crds
      namespace: flux-system
