#This file is used by Flux (NOT Kubernetes) to deploy the nginx app into the nginx namespace.
#Every 5 minutes, look in the ./networking/nginx-ingress folder in the flux-system Git repo. 
#Apply everything in that folder into the nginx namespace. 
#Wait up to 1 minute. Clean up any deleted resources.”
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 5m
  path: clusters/talos-cluster/networking/nginx-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ingress-nginx
  timeout: 2m
  wait: true
