apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: "flux-alerts"
  secretRef:
    name: discord-webhook
    key: webhookUrl

