# -----------------------------------------------------------------------------
# MetalLB Namespace Resource
#
# This manifest creates the metallb-system namespace for MetalLB components.
# - Sets required PodSecurity labels to privileged, allowing MetalLB to run
#   privileged pods (necessary for proper operation on Talos clusters).
#
# For more details, see:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
# https://kubernetes.io/docs/concepts/security/pod-security-standards/
# -----------------------------------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  #Set pod security standards to privileged for MetalLB
  # This is necessary for MetalLB to function correctly in a Talos cluster 
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
