apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: flux-alerts
  secretRef:
    name: discord-url #kube secret with the webhook URL. Create it with: kkubectl -n flux-system create secret generic discord-url --from-literal=address=insertwebhookURLHere
