# -----------------------------------------------------------------------------
# MetalLB IPAddressPool CustomResourceDefinition (CRD)
#
# This CRD defines the schema for MetalLB IPAddressPool resources.
# An IPAddressPool specifies a set of IP addresses that MetalLB can allocate
# to LoadBalancer Services in the cluster.
#
# Key fields:
# - addresses: List of IP addresses or CIDR ranges available for allocation.
# - autoAssign: If true, MetalLB will automatically assign IPs from this pool.
# - avoidBuggyIPs: If true, skips buggy IPs (optional, for advanced use).
# - serviceAllocation: (optional) Advanced allocation settings, e.g., priority.
#
# The 'status' section tracks allocation state, such as the last allocated IP
# and the total pool size.
#
# For more details, see: https://metallb.universe.tf/configuration/#ipaddresspool
# -----------------------------------------------------------------------------
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipaddresspools.metallb.io
spec:
  group: metallb.io
  names:
    kind: IPAddressPool
    listKind: IPAddressPoolList
    plural: ipaddresspools
    singular: ipaddresspool
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                addresses:
                  type: array
                  items:
                    type: string
                autoAssign:
                  type: boolean
                avoidBuggyIPs:
                  type: boolean
                serviceAllocation:
                  type: object
                  properties:
                    priority:
                      type: integer
            status:
              type: object
              properties:
                lastAllocatedIP:
                  type: string
                poolSize:
