apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32449  # Optional: fixed port; omit for dynamic. Allows access via http://<node-ip>:32449
  type: NodePort
